# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: /home/circleci/node:latest
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache:
          keys:
             - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: List contents of the directory with detailed information
          command: ls -la /home/circleci/ut_4200_code_coverage
      - run:
          name: Print npm debug logs
          command: cat /home/circleci/.npm/_logs/2023-11-16T16_23_59_504Z-debug.log
      - run:
          name: Check directory permissions
          command: ls -l /home/circleci/ut_4200_code_coverage
      - run:
          name: Verify the file path
          command: ls -l /home/circleci/ut_4200_code_coverage/package.json
      - run:
          name: Print current working directory
          command: pwd
      - run:
          name: List contents of the directory
          command: ls -la /home/circleci/ut_4200_code_coverage
      - run:
          name: Check file permissions
          command: ls -l /home/circleci/ut_4200_code_coverage/package.json
      - run:
          name: Install dependencies
          command: npm ci --prefix /home/circleci/ut_4200_code_coverage

      - run:
          name: Run tests
          command: npm test
          
      - run:
          name: Generate coverage report
          command: npm run coverage

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - store_artifacts:
          path: coverage-report
