version: 2.1

orbs:
  slack: circleci/slack@4.1.4

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: "#general"
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "This is Eric Stratford submitting the Slack assignment.",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - restore_cache:
          keys:
             - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: List contents of the directory with detailed information
          command: ls -la /home/circleci/project
      - run:
          name: Check directory permissions
          command: ls -l /home/circleci/project
      - run:
          name: Verify the file path
          command: ls -l /home/circleci/project/package.json
      - run:
          name: Print current working directory
          command: pwd
      - run:
          name: List contents of the directory
          command: ls -la /home/circleci/project
      - run:
          name: Check file permissions
          command: ls -l /home/circleci/project/package.json
      - run:
          name: Install dependencies
          command: npm ci --prefix /home/circleci/project

      - run:
          name: Run tests
          command: npm test
          
      - run:
          name: Generate coverage report
          command: npm run coverage

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - store_artifacts:
          path: coverage-report

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build

      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "fivrik"