version: 2.1

orbs:
  slack: circleci/slack@4.1.4

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: "#general"
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "This is Eric Stratford submitting the Slack assignment.",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run unit tests
          command: npm test

      - run:
          name: Generate code coverage report
          command: npm run coverage

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: coverage-report

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build

      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: "fivrik"
